//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICOMAutomagic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Top {
            get {
                return ((double)(this["Top"]));
            }
            set {
                this["Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Left {
            get {
                return ((double)(this["Left"]));
            }
            set {
                this["Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM5")]
        public string COMport {
            get {
                return ((string)(this["COMport"]));
            }
            set {
                this["COMport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1810;3500;5352;7000;10100;14000;18068;21000;24890;28000;50000")]
        public string LowerEdgesCW {
            get {
                return ((string)(this["LowerEdgesCW"]));
            }
            set {
                this["LowerEdgesCW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1840;3570;5366;7040;10130;14070;18109;21070;24920;28070;50150")]
        public string UpperEdgesCW {
            get {
                return ((string)(this["UpperEdgesCW"]));
            }
            set {
                this["UpperEdgesCW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-6;-6;-6;-6;-6;-6;-6;-6;-6;-6;-6")]
        public string RefLevelsCW {
            get {
                return ((string)(this["RefLevelsCW"]));
            }
            set {
                this["RefLevelsCW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1840;3600;5353;7040;10100;14100;18111;21150;24931;28300;50100")]
        public string LowerEdgesPhone {
            get {
                return ((string)(this["LowerEdgesPhone"]));
            }
            set {
                this["LowerEdgesPhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000;3800;5366;7200;10150;14350;18168;21450;24990;28600;50500")]
        public string UpperEdgesPhone {
            get {
                return ((string)(this["UpperEdgesPhone"]));
            }
            set {
                this["UpperEdgesPhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-9;-9;-9;-9;-9;-9;-9;-9;-9;-9;-9")]
        public string RefLevelsPhone {
            get {
                return ((string)(this["RefLevelsPhone"]));
            }
            set {
                this["RefLevelsPhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1840;3570;5352;7040;10130;14070;18089;21070;24910;28070;50300")]
        public string LowerEdgesDigital {
            get {
                return ((string)(this["LowerEdgesDigital"]));
            }
            set {
                this["LowerEdgesDigital"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1860;3600;5366;7080;10150;14100;18109;21150;24932;28110;50350")]
        public string UpperEdgesDigital {
            get {
                return ((string)(this["UpperEdgesDigital"]));
            }
            set {
                this["UpperEdgesDigital"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3;-3;-3;-3;-3;-3;-3;-3;-3;-3;-3")]
        public string RefLevelsDigital {
            get {
                return ((string)(this["RefLevelsDigital"]));
            }
            set {
                this["RefLevelsDigital"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3;-3;-3;-3;-3;-3;-3;-3;-3;-3;-3")]
        public string RefLevelsDigitalZ {
            get {
                return ((string)(this["RefLevelsDigitalZ"]));
            }
            set {
                this["RefLevelsDigitalZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3;-3;-3;-3;-3;-3;-3;-3;-3;-3;-3")]
        public string RefLevelsCWZ {
            get {
                return ((string)(this["RefLevelsCWZ"]));
            }
            set {
                this["RefLevelsCWZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-3;-3;-3;-3;-3;-3;-3;-3;-3;-3;-3")]
        public string RefLevelsPhoneZ {
            get {
                return ((string)(this["RefLevelsPhoneZ"]));
            }
            set {
                this["RefLevelsPhoneZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23;23;23;23;23;23;23;23;23;23;23")]
        public string PwrLevelsCW {
            get {
                return ((string)(this["PwrLevelsCW"]));
            }
            set {
                this["PwrLevelsCW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23;23;23;23;23;23;23;23;23;23;23")]
        public string PwrLevelsPhone {
            get {
                return ((string)(this["PwrLevelsPhone"]));
            }
            set {
                this["PwrLevelsPhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23;23;23;23;23;23;23;23;23;23;23")]
        public string PwrLevelsDigital {
            get {
                return ((string)(this["PwrLevelsDigital"]));
            }
            set {
                this["PwrLevelsDigital"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Barefoot {
            get {
                return ((bool)(this["Barefoot"]));
            }
            set {
                this["Barefoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IC-7300")]
        public string RadioModel {
            get {
                return ((string)(this["RadioModel"]));
            }
            set {
                this["RadioModel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public byte EdgeSet {
            get {
                return ((byte)(this["EdgeSet"]));
            }
            set {
                this["EdgeSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19200")]
        public int COMportSpeed {
            get {
                return ((int)(this["COMportSpeed"]));
            }
            set {
                this["COMportSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ZoomWidth {
            get {
                return ((int)(this["ZoomWidth"]));
            }
            set {
                this["ZoomWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STN1")]
        public string DXLogStation {
            get {
                return ((string)(this["DXLogStation"]));
            }
            set {
                this["DXLogStation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9888")]
        public int DXLogPort {
            get {
                return ((int)(this["DXLogPort"]));
            }
            set {
                this["DXLogPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12060")]
        public int N1MMPort {
            get {
                return ((int)(this["N1MMPort"]));
            }
            set {
                this["N1MMPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("148")]
        public byte CIVaddress {
            get {
                return ((byte)(this["CIVaddress"]));
            }
            set {
                this["CIVaddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
    }
}
